language: node_js
node_js:
  - "6"
  - "5"
script: npm run ci
cache:
  directories:
    - node_modules
env:
  - REACT_APP_DB_VERSION=test
notifications:
  email:
    recipients:
      - jamesdabbs@gmail.com
      - on_success: change
      - on_failure: always
